In [1]:
dict_ = {'no': 1,
         'reference': 1,
         'manufacturer': 'STANDARD MOTOR PRODUCTS',
         'part_number':  'UF575',
         'type_code': '7060'}

dict_

{'no': 1,
 'reference': 1,
 'manufacturer': 'STANDARD MOTOR PRODUCTS',
 'part_number': 'UF575',
 'type_code': '7060'}

In [2]:
dict_['manufacturer'] = dict_['manufacturer'].strip()
dict_['part_number'] = dict_['part_number'].replace('-', '').replace(' ', '')
dict_['type_code'] = dict_['type_code'].strip()
dict_['url'] = f'''https://www.rockauto.com/en/parts/{dict_['manufacturer']},{dict_['part_number']},Leif,{dict_['type_code']}'''

dict_

{'no': 1,
 'reference': 1,
 'manufacturer': 'STANDARD MOTOR PRODUCTS',
 'part_number': 'UF575',
 'type_code': '7060',
 'url': 'https://www.rockauto.com/en/parts/STANDARD MOTOR PRODUCTS,UF575,Leif,7060'}

In [3]:
import requests

import sys
sys.path.append('../../00.Tools')
from configuration import generate_header, generate_proxy

In [4]:
data = {'dopartsearch': '1',
        'partsearch[partnum][partsearch_007]': dict_['part_number'],
        'partsearch[manufacturer][partsearch_007]': dict_['manufacturer'],
        'partsearch[parttype][partsearch_007]': dict_['type_code'],
        'partsearch[do][partsearch_007]': '1',
        'func': 'sendparttabsearch',
        'api_json_request': '1'}
response = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                         data=data,
                         headers=generate_header(),
                         proxies=generate_proxy(),
                         timeout=(10, 15),
                         allow_redirects=False)

response.status_code

200

In [5]:
dict_2 = response.json()

dict_2

{'searchnoderesults': '<div class="ranavnode" id="nav[__GIP__1__]"><input type="hidden" autocomplete="off" id="jsn[__GIP__1__]" value="{&quot;groupindex&quot;:&quot;__GIP__1__&quot;,&quot;tab&quot;:&quot;partsearch&quot;,&quot;idepth&quot;:0,&quot;parttype&quot;:&quot;7060&quot;,&quot;catalogname&quot;:&quot;STANDARD MOTOR PRODUCTS&quot;,&quot;partnumber&quot;:&quot;UF575&quot;,&quot;nodetype&quot;:&quot;parttabsearch&quot;,&quot;expanded&quot;:true,&quot;loaded&quot;:true}" /><input type="hidden" autocomplete="off" name="navnodeunique[partsearch-7060]" id="navnodeunique[partsearch-7060]" value="__GIP__1__" /><div id="nav_o[__GIP__1__]" class="ranavouter"><div class="inner"><table class="tbl"  cellpadding="0" cellspacing="0"><tr><td class="niconspace nexpandedicon" id="navicon[__GIP__1__]"><a href="/en/parts/standard+motor+products,UF575,ignition+coil,7060" onclick="cataloglite.LinkIntercept_ToggleNavNode(&quot;__GIP__1__&quot;); return false;" tabindex="-1"><img src="/Images/1pxtransp

In [6]:
'redirect_to_url' in dict_2

False

In [7]:
from bs4 import BeautifulSoup

In [8]:
soup = BeautifulSoup(dict_2['searchnoderesults'], 'html5lib')

with open('./1.part.html', 'w', encoding='utf-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <head>
 </head>
 <body>
  <div class="ranavnode" id="nav[__GIP__1__]">
   <input autocomplete="off" id="jsn[__GIP__1__]" type="hidden" value='{"groupindex":"__GIP__1__","tab":"partsearch","idepth":0,"parttype":"7060","catalogname":"STANDARD MOTOR PRODUCTS","partnumber":"UF575","nodetype":"parttabsearch","expanded":true,"loaded":true}'/>
   <input autocomplete="off" id="navnodeunique[partsearch-7060]" name="navnodeunique[partsearch-7060]" type="hidden" value="__GIP__1__"/>
   <div class="ranavouter" id="nav_o[__GIP__1__]">
    <div class="inner">
     <table cellpadding="0" cellspacing="0" class="tbl">
      <tbody>
       <tr>
        <td class="niconspace nexpandedicon" id="navicon[__GIP__1__]">
         <a href="/en/parts/standard+motor+products,UF575,ignition+coil,7060" onclick='cataloglite.LinkIntercept_ToggleNavNode("__GIP__1__"); return false;' tabindex="-1">
          <img alt="Toggle" src="/Images/1pxtransparent.png"/>
         </a>
        </td>
        <td class="nlab

In [9]:
from parsel import Selector

In [10]:
selector = Selector(text=str(soup))

selector

<Selector query=None data='<html><head></head><body><div class="...'>

In [11]:
list_tbody = selector.xpath('//tbody[contains(@id, "listingcontainer[__GIP__")]')

list_tbody

[<Selector query='//tbody[contains(@id, "listingcontainer[__GIP__")]' data='<tbody class="listing-inner altrow-a-...'>]

In [12]:
import json

In [13]:
list_dict_2 = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_essential[__GIP__")]/@value').get()) for tbody in list_tbody]

list_dict_2

[{'groupindex': '__GIP__3__',
  'carcode': 0,
  'parttype': '7060',
  'partkey': '2415560',
  'opts': {'0-0-18-1': {'warehouse': '44840',
    'whpartnum': 'SI UF-575',
    'optionlist': '0',
    'paramcode': '0',
    'notekey': '18',
    'multiple': '1'}}}]

In [14]:
list_type_code, list_part_code = [dict_2['parttype'] for dict_2 in list_dict_2], [dict_2['partkey'] for dict_2 in list_dict_2]

list_type_code, list_part_code

(['7060'], ['2415560'])

In [15]:
import numpy as np

In [16]:
array_index_type_code = np.where(np.array(list_type_code) == dict_['type_code'])[0]

array_index_type_code

array([0])

In [17]:
list_dict_3 = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_supplemental[__GIP__")]/@value').get()) for tbody in list_tbody]

list_dict_3

[{'partnumber': 'UF575',
  'catalogname': 'STANDARD MOTOR PRODUCTS',
  'belongstolisting': '__GIP__2__',
  'sortgroup': 0,
  'sortgrouptext': '',
  'paramdesc': ''}]

In [18]:
list_part_number, list_manufacturer, list_choose = [dict_3['partnumber'] for dict_3 in list_dict_3], [dict_3['catalogname'] for dict_3 in list_dict_3], [dict_3['paramdesc'] for dict_3 in list_dict_3]

list_part_number, list_manufacturer, list_choose

(['UF575'], ['STANDARD MOTOR PRODUCTS'], [''])

In [19]:
array_index_part_number, array_index_manufacturer = np.where(np.array(list_part_number) == dict_['part_number'])[0], np.where(np.array(list_manufacturer) == dict_['manufacturer'])[0]

array_index_part_number, array_index_manufacturer

(array([0]), array([0]))

In [20]:
array_index_part = np.intersect1d(np.intersect1d(array_index_type_code, array_index_part_number), array_index_manufacturer)

array_index_part

array([0])

In [21]:
if array_index_part.size == 1:
    index_part = array_index_part[0]

index_part

np.int64(0)

In [22]:
from lxml import etree
import re
import html

In [23]:
dict_sidenote, i, list_span = {}, 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]')
for span in list_span:
    sidenote = etree.tostring(span.root).decode('utf-8')
    sidenote = re.sub(r'<.*?>', '', sidenote)
    sidenote = re.sub(r' +', ' ', sidenote)
    sidenote = html.unescape(sidenote).strip()
    if sidenote != '':
        dict_sidenote[str(i)] = sidenote
        i += 1

dict_sidenote

{'0': 'Blue Streak'}

In [24]:
list_a = list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]')
info_url = list_a[0].xpath('./@href').get() if list_a else ''
info_url = info_url if info_url.startswith('https://www.rockauto.com/en/moreinfo.php?') else f'https://www.rockauto.com/en/moreinfo.php?pk={list_part_code[index_part]}&pt={list_type_code[index_part]}&Leif=1'

info_url

'https://www.rockauto.com/en/moreinfo.php?pk=2415560&cc=0&pt=7060'

In [25]:
dict_footnote, i, list_span = {}, 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row"]/span[contains(@title, "Please make sure")]/span[@class="listing-footnote-text"]')
for span in list_span:
    footnote = etree.tostring(span.root).decode('utf-8')
    footnote = re.sub(r'<.*?>', '', footnote)
    footnote = re.sub(r' +', ' ', footnote)
    footnote = html.unescape(footnote).strip()
    if footnote != '':
        dict_footnote[str(i)] = footnote
        i += 1

dict_footnote

{'0': 'Category: Ignition Coil'}

In [26]:
list_oem, list_str_oem = [], list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/span[contains(@title, "Replaces these Alternate")]/text()').getall()
for str_oem in list_str_oem:
    list_oem_temp = [oem.strip() for oem in str_oem.split(',')]
    for oem in list_oem_temp:
        if oem != '' and oem not in list_oem:
            list_oem.append(oem)

list_oem

['06F905115E',
 '06F905115F',
 '06H905115',
 '06H905115A',
 '06H905115B',
 '07K905715',
 '07K905715A',
 '07K905715B',
 '07K905715C',
 '07K905715D',
 '07K905715E',
 '07K905715F',
 '07K905715G',
 '12336238',
 '13674387',
 '22433AA500',
 '22433AA580',
 '32005954',
 '3287677',
 '32876773',
 '33004272',
 '6H905115A',
 '6H905115B',
 '7K905715F',
 'MD363552',
 'T1031135',
 'UF50',
 'UF50T',
 'UF523',
 'UF538',
 'UF539',
 'UF566',
 'UF588',
 'UF623']

In [27]:
from urllib.parse import urljoin

In [28]:
dict_src, i, list_value = {}, 0, list_tbody[index_part].xpath('./tr[1]/td/div[contains(@class, "listing-image-space-occupy")]/input[contains(@id, "jsninlineimg[__GIP__")]/@value').getall()
for value in list_value:
    list_src = json.loads(value).get('Slots', None)
    for src in list_src:
        dict_src[str(i)] = urljoin(dict_['url'], src['ImageData']['Full'].strip())
        i += 1

dict_src

{'0': 'https://www.rockauto.com/info/154/UF-575_Front.jpg',
 '1': 'https://www.rockauto.com/info/154/UF-575_Angle.jpg',
 '2': 'https://www.rockauto.com/info/154/UF-575_Bottom.jpg',
 '3': 'https://www.rockauto.com/info/154/UF-575_Connector.jpg',
 '4': 'https://www.rockauto.com/info/154/UF-575_Left.jpg',
 '5': 'https://www.rockauto.com/info/154/UF-575_Right.jpg',
 '6': 'https://www.rockauto.com/info/154/UF-575_Top.jpg'}

In [29]:
span = list_tbody[index_part].xpath('./tr[1]/td[contains(@id, "listingtd[__GIP__") and contains(@id, "__][price]")]/span[contains(@id, "dprice[__GIP__") and contains(@id, "__][td]")]/span/span[contains(@id, "dprice[__GIP__") and contains(@id, "__][v]")]')[0]
price = etree.tostring(span.root).decode('utf-8')
price = re.sub(r'<.*?>', '', price)
price = re.sub(r' +', ' ', price)
price = html.unescape(price).strip()
dict_price = {'default': price}

i, list_td = 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div/div[contains(@class, "listing-optionchoice-multiple-container")]/span[contains(@id, "ddrepl[optionchoice[__GIP__") and contains(@id, "__]][container]")]/span[@class="hide-if-js"]/select[contains(@id, "optionchoice[__GIP__")]/option[@value!=""]')
for td in list_td:
    price = etree.tostring(td.root).decode('utf-8')
    price = re.sub(r'<.*?>', '', price)
    price = re.sub(r' +', ' ', price)
    price = html.unescape(price).strip()
    if price != '':
        if i == 0:
            dict_price['choose'] = {}
        dict_price['choose'][str(i)] = price
        i += 1

dict_price

{'default': 'Add to Cart to See Price'}

In [30]:
{'no': dict_['no'],
 'reference': dict_['reference'],
 'manufacturer': dict_['manufacturer'],
 'part_number': dict_['part_number'],
 'type_code': dict_['type_code'],
 'picture': '',
 'url': f'''https://www.rockauto.com/en/parts/{dict_['manufacturer']},{dict_['part_number']},Leif,{dict_['type_code']}''',
 'part_code': list_part_code[index_part],
 'join_mpntcpc': f'''{dict_['manufacturer']};{dict_['part_number']};{dict_['type_code']};{list_part_code[index_part]}''',
 'choose': list_choose[index_part],
 'json_sidenote': json.dumps(dict_sidenote),
 'info_url': info_url,
 'json_footnote': json.dumps(dict_footnote),
 'oem': ';'.join(list_oem),
 'json_src': json.dumps(dict_src),
 'json_price': json.dumps(dict_price)}

{'no': 1,
 'reference': 1,
 'manufacturer': 'STANDARD MOTOR PRODUCTS',
 'part_number': 'UF575',
 'type_code': '7060',
 'picture': '',
 'url': 'https://www.rockauto.com/en/parts/STANDARD MOTOR PRODUCTS,UF575,Leif,7060',
 'part_code': '2415560',
 'join_mpntcpc': 'STANDARD MOTOR PRODUCTS;UF575;7060;2415560',
 'choose': '',
 'json_sidenote': '{"0": "Blue Streak"}',
 'info_url': 'https://www.rockauto.com/en/moreinfo.php?pk=2415560&cc=0&pt=7060',
 'json_footnote': '{"0": "Category: Ignition Coil"}',
 'oem': '06F905115E;06F905115F;06H905115;06H905115A;06H905115B;07K905715;07K905715A;07K905715B;07K905715C;07K905715D;07K905715E;07K905715F;07K905715G;12336238;13674387;22433AA500;22433AA580;32005954;3287677;32876773;33004272;6H905115A;6H905115B;7K905715F;MD363552;T1031135;UF50;UF50T;UF523;UF538;UF539;UF566;UF588;UF623',
 'json_src': '{"0": "https://www.rockauto.com/info/154/UF-575_Front.jpg", "1": "https://www.rockauto.com/info/154/UF-575_Angle.jpg", "2": "https://www.rockauto.com/info/154/UF-575