In [1]:
import os

list_file = sorted(list(os.walk('./file/1.part_number'))[0][2])
while '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
while '0.null.txt' in list_file:
    list_file.remove('0.null.txt')

list_file

['crawler_1.xlsx', 'crawler_2.xlsx']

In [2]:
file = list_file[0]

file

'crawler_1.xlsx'

In [3]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [4]:
input_ = pd.read_excel(f'./file/1.part_number/{file}',
                       header=0,
                       dtype=str).fillna('')

input_['No'] = input_['No'].astype(int)

print(f'总数量：{len(input_)}')
input_['Part Number'].tolist()

总数量：507


['30250S',
 '30250SX',
 '30420S',
 '30430S',
 '30460S',
 '30460SA',
 '30460SB',
 '30470S',
 '30470SX',
 '30490S',
 '30490SA',
 '30490SAX',
 '30490SX',
 '30719S',
 '30719SHWP',
 '31007S',
 '31035S',
 '31035SX',
 '31036S',
 '31036SA',
 '31038S',
 '31038SX',
 '31041S',
 '31045S',
 '31045SA',
 '31045SX',
 '31047S',
 '31047SH',
 '31047SHWP',
 '31047SK3',
 '31047SVVT',
 '31047SX',
 '31047SXH',
 '31047SXHWP',
 '31049S',
 '31049SA',
 '31049SAH',
 '31049SAVVT1',
 '31049SAW',
 '31049SAWVVT',
 '31049SAWVVT1',
 '31049SB',
 '31049SBH',
 '31049SBX',
 '31049SBXH',
 '31049SC',
 '31049SCH',
 '31049SCX',
 '31049SCXH',
 '31049SD',
 '31049SDH',
 '31049SDX',
 '31049SDXH',
 '31049SE',
 '31049SEH',
 '31049SEK3',
 '31049SEVVT',
 '31049SF',
 '31049SFH',
 '31049SFVVT',
 '31049SG',
 '31049SGX',
 '31049SH',
 '31049SJ',
 '31049SK',
 '31049SL',
 '31049SM',
 '31049SN',
 '31049SP',
 '31049SPVVT',
 '31049SVVT1',
 '31049SVVT2',
 '31049SW',
 '31051S',
 '31051SA',
 '31051SAX',
 '31051SX',
 '31054S',
 '31055S',
 '31055SX'

In [5]:
a = 0

a

0

In [6]:
crawler_status = 'error'

crawler_status

'error'

In [7]:
import requests
import json

import sys
sys.path.append('../00.Tools')
from crawler_configuration import get_header, get_proxy

data = {'dopartsearch': '1',
        'partsearch[partnum][partsearch_007]': input_.loc[a, 'Part Number'],
        'partsearch[manufacturer][partsearch_007]': input_.loc[a, 'Manufacturer'],
        'partsearch[partgroup][partsearch_007]': input_.loc[a, 'Group'],
        'partsearch[parttype][partsearch_007]': input_.loc[a, 'Type Code'],
        'partsearch[do][partsearch_007]': '1',
        'func': 'sendparttabsearch',
        'giveback': json.dumps({}),
        'api_json_request': '1'}

b = 0
while True:
    b += 1
    print(b)
    try:
        resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                             data=data,
                             headers=get_header(),
                             proxies=get_proxy(),
                             timeout=(10, 10))
        
        if resp.status_code == 200:
            json_ = resp.json()
            
            if 'redirect_to_url' not in json_ and not resp.json()['giveback'] and 'collected_javascript' in json_:
                break
    except KeyboardInterrupt:
        break
    except:
        continue

resp

1


<Response [200]>

In [8]:
from bs4 import BeautifulSoup
from lxml import etree

soup = BeautifulSoup(json_['searchnoderesults'], 'lxml')
html = etree.HTML(str(soup))

with open('./part.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="ranavnode" id="nav[__GIP__1__]">
   <input autocomplete="off" id="jsn[__GIP__1__]" type="hidden" value='{"groupindex":"__GIP__1__","tab":"partsearch","idepth":0,"groupname":"Engine","parttype":"5756","catalogname":"MELLING","partnumber":"30250S","nodetype":"parttabsearch","expanded":true,"loaded":true}'/>
   <input autocomplete="off" id="navnodeunique[partsearch-engine-5756]" name="navnodeunique[partsearch-engine-5756]" type="hidden" value="__GIP__1__"/>
   <div class="ranavouter" id="nav_o[__GIP__1__]">
    <div class="inner">
     <table cellpadding="0" cellspacing="0" class="tbl">
      <tr>
       <td class="niconspace nexpandedicon" id="navicon[__GIP__1__]">
        <a href="/en/parts/melling,30250S,timing+chain+&amp;+component+kit,5756" onclick='cataloglite.LinkIntercept_ToggleNavNode("__GIP__1__"); return false;' tabindex="-1">
         <img alt="Toggle" src="/Images/1pxtransparent.png"/>
        </a>
       </td>
       <td class="nlabel">
        <

In [9]:
list_tbody = html.xpath('//tbody[contains(@class, "listing-inner") and (contains(@class, "altrow-a-1") or contains(@class, "altrow-a-0"))]')

list_tbody

[<Element tbody at 0x124eb9400>]

In [10]:
list_json = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_essential[__GIP__")]/@value')[0]) for tbody in list_tbody]

list_json

[{'groupindex': '__GIP__3__',
  'carcode': 0,
  'parttype': '5756',
  'partkey': '8304960',
  'opts': {'0-0-0-1': {'warehouse': '90250',
    'whpartnum': 'MEL 3-0250S@NK',
    'optionlist': '0',
    'paramcode': '0',
    'notekey': '0',
    'multiple': '1'}}}]

In [11]:
import numpy as np

array_index_type_code = np.where(np.array([json_['parttype'] for json_ in list_json]) == input_.loc[a, 'Type Code'])

array_index_type_code

(array([0]),)

In [12]:
list_key = [json_['partkey'] for json_ in list_json]

list_key

['8304960']

In [13]:
list_json = [json.loads(tbody.xpath('./tr[1]/td/input[contains(@id, "listing_data_supplemental[")]/@value')[0]) for tbody in list_tbody]

list_json

[{'partnumber': '30250S',
  'catalogname': 'MELLING',
  'belongstolisting': '__GIP__2__',
  'sortgroup': 0,
  'sortgrouptext': '',
  'paramdesc': '',
  'iskitparent': True}]

In [14]:
array_index_part_number = np.where(np.array([json_['partnumber'] for json_ in list_json]) == input_.loc[a, 'Part Number'])

array_index_part_number

(array([0]),)

In [15]:
array_index_manufacturer = np.where(np.array([json_['catalogname'] for json_ in list_json]) == input_.loc[a, 'Manufacturer'])

array_index_manufacturer

(array([0]),)

In [16]:
list_parameter = [json_['paramdesc'].strip() for json_ in list_json]

list_parameter

['']

In [17]:
array_index_part = np.intersect1d(np.intersect1d(array_index_type_code, array_index_part_number), array_index_manufacturer)

array_index_part

array([0])

In [18]:
if len(array_index_part) == 1:
    part_index = array_index_part[0]

part_index

0

In [19]:
list_note = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]/text()')
note = '\n'.join([note.strip() for note in list_note])

note

''

In [20]:
list_info = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]/@href')
info = list_info[0].strip() if list_info and list_info[0].startswith('https://www.rockauto.com/en/moreinfo.php?') else f'''https://www.rockauto.com/en/moreinfo.php?pk={list_key[part_index]}&pt={input_.loc[a, 'Type Code']}&Lennon=1'''

info

'https://www.rockauto.com/en/moreinfo.php?pk=8304960&cc=0&pt=5756'

In [21]:
import re

note_2 = etree.tostring(list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row"]')[0]).decode('utf-8')
note_2 = re.sub(r'<.*?>', '', note_2.strip())
note_2 = re.sub(r' +', ' ', note_2.strip())

note_2

'Category: Timing Chain &amp; Component Kit'

In [22]:
list_oem = list_tbody[part_index].xpath('./tr[1]/td/span[contains(@title, "Replaces these Alternate")]/text()')
oem = ','.join(list_oem)
oem = ';'.join([oem_split.strip() for oem_split in oem.split(',')])

oem

''

In [23]:
list_src = json.loads(list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value')[0])['Slots'] if list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value') else []

list_src

[{'TitlePhrase': None,
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/583/3-0250S-1-KIT__ra_m.jpg',
   'Popup': '/info/583/3-0250S-1-KIT.jpg',
   'Full': '/info/583/3-0250S-1-KIT.jpg'}},
 {'TitlePhrase': '<b>[Timing Chain Guide / Damper]</b>',
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/583/BT7015-2-SID__ra_m.jpg',
   'Popup': '/info/583/BT7015-2-SID.jpg',
   'Full': '/info/583/BT7015-2-SID.jpg'}},
 {'TitlePhrase': '<b>[Timing Chain Guide / Damper]</b>',
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/583/BG5515-1-SID__ra_m.jpg',
   'Popup': '/info/583/BG5515-1-SID.jpg',
   'Full': '/info/583/BG5515-1-SID.jpg'}},
 {'TitlePhrase': '<b>[Timing Chain]</b>',
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/583/715F-1-ANG__ra_m.jpg',
   'Popup': '/info/583/715F-1-ANG.jpg',
   'Full': '/info/583/715F-1-ANG.jpg'}},
 {'TitlePhrase': '<b>[Timing Cam Sprocket]</b>',
  'ParamCodes':

In [24]:
dict_src = {}
for i, src in zip(range(len(list_src)), list_src):
    dict_src[str(i)] = 'https://www.rockauto.com' + src['ImageData']['Full'].strip()

dict_src

{'0': 'https://www.rockauto.com/info/583/3-0250S-1-KIT.jpg',
 '1': 'https://www.rockauto.com/info/583/BT7015-2-SID.jpg',
 '2': 'https://www.rockauto.com/info/583/BG5515-1-SID.jpg',
 '3': 'https://www.rockauto.com/info/583/715F-1-ANG.jpg',
 '4': 'https://www.rockauto.com/info/583/S906A-1-ANG.jpg',
 '5': 'https://www.rockauto.com/info/583/BT5514-1-ANG.jpg',
 '6': 'https://www.rockauto.com/info/583/717F-1-ANG.jpg',
 '7': 'https://www.rockauto.com/info/583/BT7016-1-TOP.jpg',
 '8': 'https://www.rockauto.com/info/583/S899-1-ANG.jpg',
 '9': 'https://www.rockauto.com/info/583/S905-1-FRO.jpg',
 '10': 'https://www.rockauto.com/info/583/BG7019-2-SID.jpg'}

In [25]:
price = etree.tostring(list_tbody[part_index].xpath('./tr[1]/td[contains(@id, "listingtd[") and contains(@id, "][price]")]/span/span/span[contains(@id, "dprice[") and contains(@id, "][v]")]')[0]).decode('utf-8')
dict_price = {'0': re.sub(r'<.*?>', '', price.strip())}

dict_price

{'0': '$172.79'}

In [26]:
list_li = list_tbody[part_index].xpath('./tr[1]/td/div/div/span/span[contains(@id, "ddrepl[optionchoice[__")]/table/tr/td[1]/div/div/ul/li')
if list_li:
    dict_price['1'] = {}
    for j, li in zip(range(len(list_li[1:])), list_li[1:]):
        dict_price['1'][str(j)] = re.sub(r' +', ' ', re.sub(r'<.*?>', ' ', etree.tostring(li.xpath('./div[contains(@class, "outer")]/div[contains(@class, "inner")]')[0]).decode('utf-8'))).strip()

dict_price

{'0': '$172.79'}

In [27]:
df_temp = pd.DataFrame([{'No': input_.loc[a, 'No'],
                         'Group': input_.loc[a, 'Group'],
                         'Type': input_.loc[a, 'Type'],
                         'Type Code': input_.loc[a, 'Type Code'],
                         'Manufacturer': input_.loc[a, 'Manufacturer'],
                         'Part Number': input_.loc[a, 'Part Number'],
                         'Parameter': list_parameter[part_index],
                         'Json_Price': json.dumps(dict_price),
                         'Note 1': note,
                         'Note 2': note_2,
                         'OEM': oem,
                         'Picture': '',
                         'Url': input_.loc[a, 'Url'],
                         'Info': info,
                         'Json_Src': json.dumps(dict_src),
                         'Key': list_key[part_index]}])

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

No   Group                          Type Type Code Manufacturer  \
0   1  Engine  Timing Chain & Component Kit      5756      MELLING   

  Part Number Parameter        Json_Price Note 1  \
0      30250S            {"0": "$172.79"}          

                                       Note 2 OEM Picture  \
0  Category: Timing Chain &amp; Component Kit               

                                                 Url  \
0  https://www.rockauto.com/en/parts/melling,3025...   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=83...   

                                            Json_Src      Key  
0  {"0": "https://www.rockauto.com/info/583/3-025...  8304960

In [28]:
crawler_status = 'ok'

crawler_status

'ok'

In [29]:
if crawler_status == 'error':
    output_error = pd.concat([output_error, pd.DataFrame([input_.iloc[a]]).reset_index(drop=True)], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [30]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['No'],
                                                ascending=[True],
                                                ignore_index=True)
    output_correct.to_excel('./test_part.xlsx', index=False)

output_correct

No   Group                          Type Type Code Manufacturer  \
0   1  Engine  Timing Chain & Component Kit      5756      MELLING   

  Part Number Parameter        Json_Price Note 1  \
0      30250S            {"0": "$172.79"}          

                                       Note 2 OEM Picture  \
0  Category: Timing Chain &amp; Component Kit               

                                                 Url  \
0  https://www.rockauto.com/en/parts/melling,3025...   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=83...   

                                            Json_Src      Key  
0  {"0": "https://www.rockauto.com/info/583/3-025...  8304960

In [31]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['No'],
                                            ascending=[True],
                                            ignore_index=True)
    output_error.to_excel('./test_part_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []