In [1]:
import os

list_file = sorted(list(os.walk('./file/1.part_number'))[0][2])
while '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
while '0.null.txt' in list_file:
    list_file.remove('0.null.txt')

list_file

['crawler_1.xlsx', 'crawler_2.xlsx']

In [2]:
file = list_file[1]

file

'crawler_2.xlsx'

In [3]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [4]:
input_ = pd.read_excel(f'./file/1.part_number/{file}',
                       header=0,
                       dtype=str).fillna('')

input_['No'] = input_['No'].astype(int)

print(f'总数量：{len(input_)}')
input_['Part Number'].tolist()

总数量：248


['03323',
 '912001',
 '912002',
 '912003',
 '912004',
 '912005',
 '912006',
 '912007',
 '912008',
 '912009',
 '912010',
 '912011',
 '912012',
 '912013',
 '912014',
 '912015',
 '912017',
 '912018',
 '912020',
 '912021',
 '912022',
 '912023',
 '912024',
 '912025',
 '912026',
 '912028',
 '912030',
 '912031',
 '912032',
 '912033',
 '912034',
 '912035',
 '912036',
 '912037',
 '912038',
 '912039',
 '912040',
 '912041',
 '912042',
 '912043',
 '912044',
 '912045',
 '912046',
 '912047',
 '912048',
 '912049',
 '912050',
 '912052',
 '912054',
 '912055',
 '912057',
 '912060',
 '912065',
 '912066',
 '912067',
 '912070',
 '912071',
 '912073',
 '912074',
 '912075',
 '912076',
 '912077',
 '912078',
 '912079',
 '912082',
 '912083',
 '912085',
 '912086',
 '912087',
 '912088',
 '912089',
 '912090',
 '912091',
 '912092',
 '912093',
 '912094',
 '912095',
 '912096',
 '912098',
 '912099',
 '912100',
 '912101',
 '912102',
 '912103',
 '912104',
 '912111',
 '912112',
 '912113',
 '912118',
 '912119',
 '912120',


In [5]:
a = 0

a

0

In [6]:
crawler_status = 'error'

crawler_status

'error'

In [7]:
import requests
import json

import sys
sys.path.append('../00.Tools')
from crawler_configuration import get_header, get_proxy

data = {'dopartsearch': '1',
        'partsearch[partnum][partsearch_007]': input_.loc[a, 'Part Number'],
        'partsearch[manufacturer][partsearch_007]': input_.loc[a, 'Manufacturer'],
        'partsearch[partgroup][partsearch_007]': input_.loc[a, 'Group'],
        'partsearch[parttype][partsearch_007]': input_.loc[a, 'Type Code'],
        'partsearch[do][partsearch_007]': '1',
        'func': 'sendparttabsearch',
        'giveback': json.dumps({}),
        'api_json_request': '1'}

b = 0
while True:
    b += 1
    print(b)
    try:
        resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                             data=data,
                             headers=get_header(),
                             proxies=get_proxy(),
                             timeout=(10, 10))
        
        if resp.status_code == 200:
            json_ = resp.json()
            
            if 'redirect_to_url' not in json_ and not resp.json()['giveback'] and 'collected_javascript' in json_:
                break
    except KeyboardInterrupt:
        break
    except:
        continue

resp

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33


<Response [200]>

In [8]:
from bs4 import BeautifulSoup
from lxml import etree

soup = BeautifulSoup(json_['searchnoderesults'], 'lxml')
html = etree.HTML(str(soup))

with open('./part.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="ranavnode" id="nav[__GIP__1__]">
   <input autocomplete="off" id="jsn[__GIP__1__]" type="hidden" value='{"groupindex":"__GIP__1__","tab":"partsearch","idepth":0,"groupname":"Interior","parttype":"1360","catalogname":"DORMAN","partnumber":"03323","nodetype":"parttabsearch","expanded":true,"loaded":true}'/>
   <input autocomplete="off" id="navnodeunique[partsearch-interior-1360]" name="navnodeunique[partsearch-interior-1360]" type="hidden" value="__GIP__1__"/>
   <div class="ranavouter" id="nav_o[__GIP__1__]">
    <div class="inner">
     <table cellpadding="0" cellspacing="0" class="tbl">
      <tr>
       <td class="niconspace nexpandedicon" id="navicon[__GIP__1__]">
        <a href="/en/parts/dorman,03323,hood+release+cable,1360" onclick='cataloglite.LinkIntercept_ToggleNavNode("__GIP__1__"); return false;' tabindex="-1">
         <img alt="Toggle" src="/Images/1pxtransparent.png"/>
        </a>
       </td>
       <td class="nlabel">
        <a class="nav

In [9]:
list_tbody = html.xpath('//tbody[contains(@class, "listing-inner") and (contains(@class, "altrow-a-1") or contains(@class, "altrow-a-0"))]')

list_tbody

[<Element tbody at 0x12726ca00>]

In [10]:
list_json = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_essential[__GIP__")]/@value')[0]) for tbody in list_tbody]

list_json

[{'groupindex': '__GIP__3__',
  'carcode': 0,
  'parttype': '1360',
  'partkey': '261306',
  'opts': {'0-0-0-1': {'warehouse': '92829',
    'whpartnum': 'DOR 03323',
    'optionlist': '0',
    'paramcode': '0',
    'notekey': '0',
    'multiple': '1'}}}]

In [11]:
import numpy as np

array_index_type_code = np.where(np.array([json_['parttype'] for json_ in list_json]) == input_.loc[a, 'Type Code'])

array_index_type_code

(array([0]),)

In [12]:
list_key = [json_['partkey'] for json_ in list_json]

list_key

['261306']

In [13]:
list_json = [json.loads(tbody.xpath('./tr[1]/td/input[contains(@id, "listing_data_supplemental[")]/@value')[0]) for tbody in list_tbody]

list_json

[{'partnumber': '03323',
  'catalogname': 'DORMAN',
  'belongstolisting': '__GIP__2__',
  'sortgroup': 0,
  'sortgrouptext': '',
  'paramdesc': ''}]

In [14]:
array_index_part_number = np.where(np.array([json_['partnumber'] for json_ in list_json]) == input_.loc[a, 'Part Number'])

array_index_part_number

(array([0]),)

In [15]:
array_index_manufacturer = np.where(np.array([json_['catalogname'] for json_ in list_json]) == input_.loc[a, 'Manufacturer'])

array_index_manufacturer

(array([0]),)

In [16]:
list_parameter = [json_['paramdesc'].strip() for json_ in list_json]

list_parameter

['']

In [17]:
array_index_part = np.intersect1d(np.intersect1d(array_index_type_code, array_index_part_number), array_index_manufacturer)

array_index_part

array([0])

In [18]:
if len(array_index_part) == 1:
    part_index = array_index_part[0]

part_index

0

In [19]:
list_note = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]/text()')
note = '\n'.join([note.strip() for note in list_note])

note

'Hood Release Cable Kit; Chrysler/Ford/GM; Kit contains 3 handles, (1) 94" cable and attaching hardware'

In [20]:
list_info = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]/@href')
info = list_info[0].strip() if list_info and list_info[0].startswith('https://www.rockauto.com/en/moreinfo.php?') else f'''https://www.rockauto.com/en/moreinfo.php?pk={list_key[part_index]}&pt={input_.loc[a, 'Type Code']}&Lennon=1'''

info

'https://www.rockauto.com/en/moreinfo.php?pk=261306&cc=0&pt=1360'

In [21]:
import re

note_2 = etree.tostring(list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row"]')[0]).decode('utf-8')
note_2 = re.sub(r'<.*?>', '', note_2.strip())
note_2 = re.sub(r' +', ' ', note_2.strip())

note_2

'Category: Hood Release Cable'

In [22]:
oem = ','.join(list_tbody[part_index].xpath('./tr[1]/td/span[contains(@title, "Replaces these Alternate")]/text()'))
list_oem = [oem.strip() for oem in oem.split(',')]
oem = ';'.join(sorted(list_oem))

oem

''

In [23]:
list_src = json.loads(list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value')[0])['Slots'] if list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value') else []

list_src

[{'TitlePhrase': None,
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/42/03323-007__ra_m.jpg',
   'Popup': '/info/42/03323-007.jpg',
   'Full': '/info/42/03323-007.jpg'}}]

In [24]:
dict_src = {}
for i, src in zip(range(len(list_src)), list_src):
    dict_src[str(i)] = 'https://www.rockauto.com' + src['ImageData']['Full'].strip()

dict_src

{'0': 'https://www.rockauto.com/info/42/03323-007.jpg'}

In [25]:
price = etree.tostring(list_tbody[part_index].xpath('./tr[1]/td[contains(@id, "listingtd[") and contains(@id, "][price]")]/span/span/span[contains(@id, "dprice[") and contains(@id, "][v]")]')[0]).decode('utf-8')
dict_price = {'0': re.sub(r'<.*?>', '', price.strip())}

dict_price

{'0': '$16.65'}

In [26]:
list_li = list_tbody[part_index].xpath('./tr[1]/td/div/div/span/span[contains(@id, "ddrepl[optionchoice[__")]/table/tr/td[1]/div/div/ul/li')
if list_li:
    dict_price['1'] = {}
    for j, li in zip(range(len(list_li[1:])), list_li[1:]):
        dict_price['1'][str(j)] = re.sub(r' +', ' ', re.sub(r'<.*?>', ' ', etree.tostring(li.xpath('./div[contains(@class, "outer")]/div[contains(@class, "inner")]')[0]).decode('utf-8'))).strip()

dict_price

{'0': '$16.65'}

In [27]:
df_temp = pd.DataFrame([{'No': input_.loc[a, 'No'],
                         'Group': input_.loc[a, 'Group'],
                         'Type': input_.loc[a, 'Type'],
                         'Type Code': input_.loc[a, 'Type Code'],
                         'Manufacturer': input_.loc[a, 'Manufacturer'],
                         'Part Number': input_.loc[a, 'Part Number'],
                         'Parameter': list_parameter[part_index],
                         'Json_Price': json.dumps(dict_price),
                         'Note 1': note,
                         'Note 2': note_2,
                         'OEM': oem,
                         'Picture': '',
                         'Url': input_.loc[a, 'Url'],
                         'Info': info,
                         'Json_Src': json.dumps(dict_src),
                         'Key': list_key[part_index]}])

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

No     Group                Type Type Code Manufacturer Part Number  \
0   1  Interior  Hood Release Cable      1360       DORMAN       03323   

  Parameter       Json_Price  \
0            {"0": "$16.65"}   

                                              Note 1  \
0  Hood Release Cable Kit; Chrysler/Ford/GM; Kit ...   

                         Note 2 OEM Picture  \
0  Category: Hood Release Cable               

                                                 Url  \
0  https://www.rockauto.com/en/parts/dorman,03323...   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=26...   

                                            Json_Src     Key  
0  {"0": "https://www.rockauto.com/info/42/03323-...  261306

In [28]:
crawler_status = 'ok'

crawler_status

'ok'

In [29]:
if crawler_status == 'error':
    output_error = pd.concat([output_error, pd.DataFrame([input_.iloc[a]]).reset_index(drop=True)], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [30]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['No'],
                                                ascending=[True],
                                                ignore_index=True)
    output_correct.to_excel('./test_part.xlsx', index=False)

output_correct

No     Group                Type Type Code Manufacturer Part Number  \
0   1  Interior  Hood Release Cable      1360       DORMAN       03323   

  Parameter       Json_Price  \
0            {"0": "$16.65"}   

                                              Note 1  \
0  Hood Release Cable Kit; Chrysler/Ford/GM; Kit ...   

                         Note 2 OEM Picture  \
0  Category: Hood Release Cable               

                                                 Url  \
0  https://www.rockauto.com/en/parts/dorman,03323...   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=26...   

                                            Json_Src     Key  
0  {"0": "https://www.rockauto.com/info/42/03323-...  261306

In [31]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['No'],
                                            ascending=[True],
                                            ignore_index=True)
    output_error.to_excel('./test_part_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []