In [1]:
param_date = '20240715'

In [2]:
import os

list_file = sorted(list(os.walk(f'./{param_date}/6.part_number_2'))[0][2])
while '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
while '0.null.txt' in list_file:
    list_file.remove('0.null.txt')

list_file

['group_1.Apparel & Gifts.xlsx',
 'group_10.Electrical-Switch & Relay-serial_1.xlsx',
 'group_10.Electrical-Switch & Relay-serial_2.xlsx',
 'group_10.Electrical-Switch & Relay-serial_3.xlsx',
 'group_11.Engine-serial_1.xlsx',
 'group_11.Engine-serial_10.xlsx',
 'group_11.Engine-serial_2.xlsx',
 'group_11.Engine-serial_3.xlsx',
 'group_11.Engine-serial_4.xlsx',
 'group_11.Engine-serial_5.xlsx',
 'group_11.Engine-serial_6.xlsx',
 'group_11.Engine-serial_7.xlsx',
 'group_11.Engine-serial_8.xlsx',
 'group_11.Engine-serial_9.xlsx',
 'group_12.Exhaust & Emission-serial_1.xlsx',
 'group_12.Exhaust & Emission-serial_2.xlsx',
 'group_12.Exhaust & Emission-serial_3.xlsx',
 'group_12.Exhaust & Emission-serial_4.xlsx',
 'group_12.Exhaust & Emission-serial_5.xlsx',
 'group_12.Exhaust & Emission-serial_6.xlsx',
 'group_13.Fuel & Air-serial_1.xlsx',
 'group_13.Fuel & Air-serial_2.xlsx',
 'group_13.Fuel & Air-serial_3.xlsx',
 'group_13.Fuel & Air-serial_4.xlsx',
 'group_13.Fuel & Air-serial_5.xlsx',
 

In [3]:
file = list_file[0]

file

'group_1.Apparel & Gifts.xlsx'

In [4]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [5]:
input_ = pd.read_excel(f'./{param_date}/6.part_number_2/{file}',
                       header=0,
                       dtype=str).fillna('')

input_['Group No'] = input_['Group No'].astype(int)
input_['Type No'] = input_['Type No'].astype(int)
input_['Manufacturer No'] = input_['Manufacturer No'].astype(int)
input_['Part No'] = input_['Part No'].astype(int)

print(f'总数量：{len(input_)}')
input_['Part Number'].tolist()

总数量：33


['GIFTCERT100',
 'GIFTCERT25',
 'GIFTCERT50',
 'GIFTCERT75',
 'GIFTCERTVAR',
 'B1',
 'B2',
 'B3',
 'BLACKHAT',
 'H1',
 'H2',
 'LANYARD',
 'MAGPACK',
 'A507',
 'BUMPERDECAL',
 'BUMPERDECAL2',
 'DECALCOMBO',
 'DECALCOMBO2',
 'DECALCOMBO3',
 'WINDOWDECAL',
 'T1',
 'T10',
 'T11',
 'T2',
 'T3',
 'T3C',
 'T3R',
 'T4',
 'T5',
 'T6',
 'T7',
 'T8',
 'T9']

In [6]:
a = 0

a

0

In [7]:
crawler_status = 'error'

crawler_status

'error'

In [8]:
import requests
import json

import sys
sys.path.append('../../00.Tools')
from crawler_configuration import get_header, get_proxy

data = {'dopartsearch': '1',
        'partsearch[partnum][partsearch_007]': input_.loc[a, 'Part Number'],
        'partsearch[manufacturer][partsearch_007]': input_.loc[a, 'Manufacturer'],
        'partsearch[partgroup][partsearch_007]': input_.loc[a, 'Group'],
        'partsearch[parttype][partsearch_007]': input_.loc[a, 'Type Code'],
        'partsearch[do][partsearch_007]': '1',
        'func': 'sendparttabsearch',
        'giveback': json.dumps({}),
        'api_json_request': '1'}

b = 0
while True:

    while True:
        b += 1
        print(b)
        try:
            resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                                 data=data,
                                 headers=get_header(),
                                 proxies=get_proxy(),
                                 timeout=(10, 10))
            break
        except:
            continue

    if resp.status_code == 200:
        break

resp

1


<Response [200]>

In [9]:
json_ = resp.json()

json_

{'giveback': [],
 'searchnoderesults': '<div class="ranavnode" id="nav[__GIP__1__]"><input type="hidden" autocomplete="off" id="jsn[__GIP__1__]" value="{&quot;groupindex&quot;:&quot;__GIP__1__&quot;,&quot;tab&quot;:&quot;partsearch&quot;,&quot;idepth&quot;:0,&quot;groupname&quot;:&quot;Apparel &amp; Gifts&quot;,&quot;parttype&quot;:&quot;260&quot;,&quot;catalogname&quot;:&quot;ROCKAUTO&quot;,&quot;partnumber&quot;:&quot;GIFTCERT100&quot;,&quot;nodetype&quot;:&quot;parttabsearch&quot;,&quot;expanded&quot;:true,&quot;loaded&quot;:true}" /><input type="hidden" autocomplete="off" name="navnodeunique[partsearch-apparel &amp; gifts-260]" id="navnodeunique[partsearch-apparel &amp; gifts-260]" value="__GIP__1__" /><div id="nav_o[__GIP__1__]" class="ranavouter"><div class="inner"><table class="tbl"  cellpadding="0" cellspacing="0"><tr><td class="niconspace nexpandedicon" id="navicon[__GIP__1__]"><a href="/en/parts/rockauto,GIFTCERT100,gift+certificate,260" onclick="cataloglite.LinkIntercept_Tog

In [10]:
'redirect_to_url' in json_

False

In [11]:
not resp.json()['giveback'] and 'collected_javascript' in json_

True

In [12]:
from bs4 import BeautifulSoup
from lxml import etree

soup = BeautifulSoup(json_['searchnoderesults'], 'lxml')
html = etree.HTML(str(soup))

with open('./part_1.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="ranavnode" id="nav[__GIP__1__]">
   <input autocomplete="off" id="jsn[__GIP__1__]" type="hidden" value='{"groupindex":"__GIP__1__","tab":"partsearch","idepth":0,"groupname":"Apparel &amp; Gifts","parttype":"260","catalogname":"ROCKAUTO","partnumber":"GIFTCERT100","nodetype":"parttabsearch","expanded":true,"loaded":true}'/>
   <input autocomplete="off" id="navnodeunique[partsearch-apparel &amp; gifts-260]" name="navnodeunique[partsearch-apparel &amp; gifts-260]" type="hidden" value="__GIP__1__"/>
   <div class="ranavouter" id="nav_o[__GIP__1__]">
    <div class="inner">
     <table cellpadding="0" cellspacing="0" class="tbl">
      <tr>
       <td class="niconspace nexpandedicon" id="navicon[__GIP__1__]">
        <a href="/en/parts/rockauto,GIFTCERT100,gift+certificate,260" onclick='cataloglite.LinkIntercept_ToggleNavNode("__GIP__1__"); return false;' tabindex="-1">
         <img alt="Toggle" src="/Images/1pxtransparent.png"/>
        </a>
       </td>
     

In [13]:
list_tbody = html.xpath('//tbody[contains(@class, "listing-inner") and (contains(@class, "altrow-a-1") or contains(@class, "altrow-a-0"))]')

list_tbody

[<Element tbody at 0x11cdaa180>]

In [14]:
list_json = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_essential[__GIP__")]/@value')[0]) for tbody in list_tbody]

list_json

[{'groupindex': '__GIP__3__',
  'carcode': 0,
  'parttype': '260',
  'partkey': '368852',
  'opts': {'6-Email-0-1': {'warehouse': '53717',
    'whpartnum': '999 GIFTCERT100E',
    'optionlist': '6',
    'paramcode': 'Email',
    'notekey': '0',
    'multiple': '1'},
   '6-Paper-0-1': {'warehouse': '53714',
    'whpartnum': '999 GIFTCERT100P',
    'optionlist': '6',
    'paramcode': 'Paper',
    'notekey': '0',
    'multiple': '1'}}}]

In [15]:
import numpy as np

array_index_type_code = np.where(np.array([json_['parttype'] for json_ in list_json]) == input_.loc[a, 'Type Code'])

array_index_type_code

(array([0]),)

In [16]:
list_key = [json_['partkey'] for json_ in list_json]

list_key

['368852']

In [17]:
list_json = [json.loads(tbody.xpath('./tr[1]/td/input[contains(@id, "listing_data_supplemental[")]/@value')[0]) for tbody in list_tbody]

list_json

[{'partnumber': 'GIFTCERT100',
  'catalogname': 'ROCKAUTO',
  'belongstolisting': '__GIP__2__',
  'sortgroup': 0,
  'sortgrouptext': '',
  'paramdesc': 'Format'}]

In [18]:
array_index_part_number = np.where(np.array([json_['partnumber'] for json_ in list_json]) == input_.loc[a, 'Part Number'])

array_index_part_number

(array([0]),)

In [19]:
array_index_manufacturer = np.where(np.array([json_['catalogname'] for json_ in list_json]) == input_.loc[a, 'Manufacturer'])

array_index_manufacturer

(array([0]),)

In [20]:
list_parameter = [json_['paramdesc'].strip() for json_ in list_json]

list_parameter

['Format']

In [21]:
array_index_part = np.intersect1d(np.intersect1d(array_index_type_code, array_index_part_number), array_index_manufacturer)

array_index_part

array([0])

In [22]:
len(array_index_part) == 1

True

In [23]:
part_index = array_index_part[0]

part_index

0

In [24]:
list_note = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]/text()')
note = '\n'.join([note.strip() for note in list_note])

note

'$100 Gift Certificate'

In [25]:
list_info = list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]/@href')
info = list_info[0].strip() if list_info and list_info[0].startswith('https://www.rockauto.com/en/moreinfo.php?') else ''

info

'https://www.rockauto.com/en/moreinfo.php?pk=368852&cc=0&pt=260'

In [26]:
import re

note_2 = etree.tostring(list_tbody[part_index].xpath('./tr[1]/td/div[@class="listing-text-row"]')[0]).decode('utf-8')
note_2 = re.sub(r'<.*?>', '', note_2.strip())
note_2 = re.sub(r' +', ' ', note_2.strip())

note_2

'Category: Gift Certificate'

In [27]:
array_index_part_number = np.where(np.array([json_['partnumber'] for json_ in list_json]) == input_.loc[a, 'Part Number'])

array_index_part_number

(array([0]),)

In [28]:
list_oem = list_tbody[part_index].xpath('./tr[1]/td/span[contains(@title, "Replaces these Alternate")]/text()')
oem = ','.join(list_oem)
oem = ';'.join([oem_split.strip() for oem_split in oem.split(',')])

oem

'GIFTCERT100E;GIFTCERT100P'

In [29]:
list_src = json.loads(list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value')[0])['Slots'] if list_tbody[part_index].xpath('./tr[1]/td/div/input[contains(@id, "jsninlineimg[")]/@value') else []

list_src

[{'TitlePhrase': None,
  'ParamCodes': [None],
  'Type': 'Single',
  'ImageData': {'Thumb': '/info/999/GCcat_100__ra_m.jpg',
   'Popup': '/info/999/GCcat_100.jpg',
   'Full': '/info/999/GCcat_100.jpg'}}]

In [30]:
dict_src = {}
for i, src in zip(range(len(list_src)), list_src):
    dict_src[str(i)] = 'https://www.rockauto.com' + src['ImageData']['Full'].strip()

dict_src

{'0': 'https://www.rockauto.com/info/999/GCcat_100.jpg'}

In [31]:
df_temp = pd.DataFrame([{'Group No': input_.loc[a, 'Group No'],
                         'Group': input_.loc[a, 'Group'],
                         'Type No': input_.loc[a, 'Type No'],
                         'Type': input_.loc[a, 'Type'],
                         'Type Code': input_.loc[a, 'Type Code'],
                         'Manufacturer No': input_.loc[a, 'Manufacturer No'],
                         'Manufacturer': input_.loc[a, 'Manufacturer'],
                         'Tab 2 Url': input_.loc[a, 'Tab 2 Url'],
                         'Part No': input_.loc[a, 'Part No'],
                         'Part Number': input_.loc[a, 'Part Number'],
                         'Url': input_.loc[a, 'Url'],
                         'Key': list_key[part_index],
                         'JOIN_MPNTCK': f'''{input_.loc[a, 'Manufacturer']};{input_.loc[a, 'Part Number']};{input_.loc[a, 'Type Code']};{list_key[part_index]}''',
                         'Tab 2 Note 1': note,
                         'Tab 2 Note 2': note_2,
                         'Parameter': list_parameter[part_index],
                         'OEM': oem,
                         'Info': info,
                         'Json_Src': json.dumps(dict_src)}])

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

Group No            Group  Type No              Type Type Code  \
0         1  Apparel & Gifts        1  Gift Certificate       260   

   Manufacturer No Manufacturer  \
0                1     ROCKAUTO   

                                           Tab 2 Url  Part No  Part Number  \
0  https://www.rockauto.com/en/parts/ROCKAUTO,Gif...        1  GIFTCERT100   

                                                 Url     Key  \
0  https://www.rockauto.com/en/parts/rockauto,GIF...  368852   

                       JOIN_MPNTCK           Tab 2 Note 1  \
0  ROCKAUTO;GIFTCERT100;260;368852  $100 Gift Certificate   

                 Tab 2 Note 2 Parameter                        OEM  \
0  Category: Gift Certificate    Format  GIFTCERT100E;GIFTCERT100P   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=36...   

                                            Json_Src  
0  {"0": "https://www.rockauto.com/info/999/GCcat...

In [32]:
crawler_status = 'ok'

crawler_status

'ok'

In [33]:
if crawler_status == 'error':
    df_temp = pd.DataFrame([{'Group No': input_.loc[a, 'Group No'],
                             'Group': input_.loc[a, 'Group'],
                             'Type No': input_.loc[a, 'Type No'],
                             'Type': input_.loc[a, 'Type'],
                             'Type Code': input_.loc[a, 'Type Code'],
                             'Manufacturer No': input_.loc[a, 'Manufacturer No'],
                             'Manufacturer': input_.loc[a, 'Manufacturer'],
                             'Tab 2 Url': input_.loc[a, 'Tab 2 Url'],
                             'Part No': input_.loc[a, 'Part No'],
                             'Part Number': input_.loc[a, 'Part Number'],
                             'Url': input_.loc[a, 'Url']}])

    output_error = pd.concat([output_error, df_temp], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [34]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['Group No', 'Type No', 'Manufacturer No', 'Part No'],
                                                ascending=[True, True, True, True],
                                                ignore_index=True)
    output_correct.to_excel('./test_part_1.xlsx', index=False)

output_correct

Group No            Group  Type No              Type Type Code  \
0         1  Apparel & Gifts        1  Gift Certificate       260   

   Manufacturer No Manufacturer  \
0                1     ROCKAUTO   

                                           Tab 2 Url  Part No  Part Number  \
0  https://www.rockauto.com/en/parts/ROCKAUTO,Gif...        1  GIFTCERT100   

                                                 Url     Key  \
0  https://www.rockauto.com/en/parts/rockauto,GIF...  368852   

                       JOIN_MPNTCK           Tab 2 Note 1  \
0  ROCKAUTO;GIFTCERT100;260;368852  $100 Gift Certificate   

                 Tab 2 Note 2 Parameter                        OEM  \
0  Category: Gift Certificate    Format  GIFTCERT100E;GIFTCERT100P   

                                                Info  \
0  https://www.rockauto.com/en/moreinfo.php?pk=36...   

                                            Json_Src  
0  {"0": "https://www.rockauto.com/info/999/GCcat...

In [35]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['Group No', 'Type No', 'Manufacturer No', 'Part No'],
                                            ascending=[True, True, True, True],
                                            ignore_index=True)
    output_error.to_excel('./test_part_1_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []