In [1]:
dict_ = {'kit_type': 'Timing Chain',
         'kit_no': 1,
         'kit_type_code': '5724',
         'kit_manufacturer': 'MELLING',
         'kit_part_number': '715F',
         'kit_url': 'https://www.rockauto.com/en/parts/MELLING,715F,Timing Chain,5724&Lennon=1',
         'kit_part_code': '8306448',
         'kit_join_mpntcpc': 'MELLING;715F;5724;8306448',
         'kit_info_url': 'https://www.rockauto.com/en/moreinfo.php?pk=8306448&cc=0&pt=5724',
         'kit_json_src': '{"0": "https://www.rockauto.com/info/583/715F-1-ANG.jpg"}'}

dict_

{'kit_type': 'Timing Chain',
 'kit_no': 1,
 'kit_type_code': '5724',
 'kit_manufacturer': 'MELLING',
 'kit_part_number': '715F',
 'kit_url': 'https://www.rockauto.com/en/parts/MELLING,715F,Timing Chain,5724&Lennon=1',
 'kit_part_code': '8306448',
 'kit_join_mpntcpc': 'MELLING;715F;5724;8306448',
 'kit_info_url': 'https://www.rockauto.com/en/moreinfo.php?pk=8306448&cc=0&pt=5724',
 'kit_json_src': '{"0": "https://www.rockauto.com/info/583/715F-1-ANG.jpg"}'}

In [2]:
import requests

import sys
sys.path.append('../00.Tools')
from configuration import generate_header, generate_proxy

In [3]:
data = {'dopartsearch': '1',
        'partsearch[partnum][partsearch_007]': dict_['kit_part_number'],
        'partsearch[manufacturer][partsearch_007]': dict_['kit_manufacturer'],
        'partsearch[parttype][partsearch_007]': dict_['kit_type_code'],
        'partsearch[do][partsearch_007]': '1',
        'func': 'sendparttabsearch',
        'api_json_request': '1'}
response = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                         data=data,
                         headers=generate_header(),
                         proxies=generate_proxy(),
                         timeout=(10, 15),
                         allow_redirects=False)

response.status_code

200

In [4]:
dict_2 = response.json()

dict_2

{'searchnoderesults': '<div class="ranavnode" id="nav[__GIP__1__]"><input type="hidden" autocomplete="off" id="jsn[__GIP__1__]" value="{&quot;groupindex&quot;:&quot;__GIP__1__&quot;,&quot;tab&quot;:&quot;partsearch&quot;,&quot;idepth&quot;:0,&quot;parttype&quot;:&quot;5724&quot;,&quot;catalogname&quot;:&quot;MELLING&quot;,&quot;partnumber&quot;:&quot;715F&quot;,&quot;nodetype&quot;:&quot;parttabsearch&quot;,&quot;expanded&quot;:true,&quot;loaded&quot;:true}" /><input type="hidden" autocomplete="off" name="navnodeunique[partsearch-5724]" id="navnodeunique[partsearch-5724]" value="__GIP__1__" /><div id="nav_o[__GIP__1__]" class="ranavouter"><div class="inner"><table class="tbl"  cellpadding="0" cellspacing="0"><tr><td class="niconspace nexpandedicon" id="navicon[__GIP__1__]"><a href="/en/parts/melling,715F,timing+chain,5724" onclick="cataloglite.LinkIntercept_ToggleNavNode(&quot;__GIP__1__&quot;); return false;" tabindex="-1"><img src="/Images/1pxtransparent.png" alt="Toggle"></a></td><t

In [5]:
'redirect_to_url' in dict_2

False

In [6]:
from bs4 import BeautifulSoup

In [7]:
soup = BeautifulSoup(dict_2['searchnoderesults'], 'html5lib')

with open('./7.kit_part.html', 'w', encoding='utf-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <head>
 </head>
 <body>
  <div class="ranavnode" id="nav[__GIP__1__]">
   <input autocomplete="off" id="jsn[__GIP__1__]" type="hidden" value='{"groupindex":"__GIP__1__","tab":"partsearch","idepth":0,"parttype":"5724","catalogname":"MELLING","partnumber":"715F","nodetype":"parttabsearch","expanded":true,"loaded":true}'/>
   <input autocomplete="off" id="navnodeunique[partsearch-5724]" name="navnodeunique[partsearch-5724]" type="hidden" value="__GIP__1__"/>
   <div class="ranavouter" id="nav_o[__GIP__1__]">
    <div class="inner">
     <table cellpadding="0" cellspacing="0" class="tbl">
      <tbody>
       <tr>
        <td class="niconspace nexpandedicon" id="navicon[__GIP__1__]">
         <a href="/en/parts/melling,715F,timing+chain,5724" onclick='cataloglite.LinkIntercept_ToggleNavNode("__GIP__1__"); return false;' tabindex="-1">
          <img alt="Toggle" src="/Images/1pxtransparent.png"/>
         </a>
        </td>
        <td class="nlabel">
         <a class="navlabellin

In [8]:
from parsel import Selector

In [9]:
selector = Selector(text=str(soup))

selector

<Selector query=None data='<html><head></head><body><div class="...'>

In [10]:
list_tbody = selector.xpath('//tbody[contains(@id, "listingcontainer[__GIP__")]')

list_tbody

[<Selector query='//tbody[contains(@id, "listingcontainer[__GIP__")]' data='<tbody class="listing-inner altrow-a-...'>]

In [11]:
import json

In [12]:
list_dict_2 = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_essential[__GIP__")]/@value').get()) for tbody in list_tbody]

list_dict_2

[{'groupindex': '__GIP__3__',
  'carcode': 0,
  'parttype': '5724',
  'partkey': '8306448',
  'opts': {'0-0-0-1': {'warehouse': 0,
    'whpartnum': '',
    'optionlist': '0',
    'paramcode': '0',
    'notekey': '0',
    'multiple': 1}}}]

In [13]:
list_type_code, list_part_code = [dict_2['parttype'] for dict_2 in list_dict_2], [dict_2['partkey'] for dict_2 in list_dict_2]

list_type_code, list_part_code

(['5724'], ['8306448'])

In [14]:
import numpy as np

In [15]:
array_index_type_code, array_index_part_code = np.where(np.array(list_type_code) == dict_['kit_type_code'])[0], np.where(np.array(list_part_code) == dict_['kit_part_code'])[0]

array_index_type_code, array_index_part_code

(array([0]), array([0]))

In [16]:
list_dict_3 = [json.loads(tbody.xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/input[contains(@id, "listing_data_supplemental[__GIP__")]/@value').get()) for tbody in list_tbody]

list_dict_3

[{'partnumber': '715F',
  'catalogname': 'MELLING',
  'belongstolisting': '__GIP__2__',
  'sortgroup': 0,
  'sortgrouptext': '',
  'paramdesc': ''}]

In [17]:
list_part_number, list_manufacturer, list_choose = [dict_3['partnumber'] for dict_3 in list_dict_3], [dict_3['catalogname'] for dict_3 in list_dict_3], [dict_3['paramdesc'] for dict_3 in list_dict_3]

list_part_number, list_manufacturer, list_choose

(['715F'], ['MELLING'], [''])

In [18]:
array_index_part_number, array_index_manufacturer = np.where(np.array(list_part_number) == dict_['kit_part_number'])[0], np.where(np.array(list_manufacturer) == dict_['kit_manufacturer'])[0]

array_index_part_number, array_index_manufacturer

(array([0]), array([0]))

In [19]:
array_index_part = np.intersect1d(np.intersect1d(np.intersect1d(array_index_type_code, array_index_part_code), array_index_part_number), array_index_manufacturer)

array_index_part

array([0])

In [20]:
if array_index_part.size == 1:
    index_part = array_index_part[0]

index_part

np.int64(0)

In [21]:
from lxml import etree
import re
import html

In [22]:
dict_sidenote, i, list_span = {}, 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row-moreinfo-truck"]/span[@class="span-link-underline-remover"]')
for span in list_span:
    sidenote = etree.tostring(span.root).decode('utf-8')
    sidenote = re.sub(r'<.*?>', '', sidenote)
    sidenote = re.sub(r' +', ' ', sidenote)
    sidenote = html.unescape(sidenote).strip()
    if sidenote != '':
        dict_sidenote[str(i)] = sidenote
        i += 1

dict_sidenote

{}

In [23]:
list_a = list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row-moreinfo-truck"]/a[@class="ra-btn ra-btn-moreinfo"]')
info_url = list_a[0].xpath('./@href').get() if list_a else ''
info_url = info_url if info_url.startswith('https://www.rockauto.com/en/moreinfo.php?') else dict_['kit_info_url']

info_url

'https://www.rockauto.com/en/moreinfo.php?pk=8306448&cc=0&pt=5724'

In [24]:
dict_footnote, i, list_span = {}, 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div[@class="listing-text-row"]/span[contains(@title, "Please make sure")]/span[@class="listing-footnote-text"]')
for span in list_span:
    footnote = etree.tostring(span.root).decode('utf-8')
    footnote = re.sub(r'<.*?>', '', footnote)
    footnote = re.sub(r' +', ' ', footnote)
    footnote = html.unescape(footnote).strip()
    if footnote != '':
        dict_footnote[str(i)] = footnote
        i += 1

dict_footnote

{'0': 'Category: Timing Chain'}

In [25]:
list_oem, list_str_oem = [], list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/span[contains(@title, "Replaces these Alternate")]/text()').getall()
for str_oem in list_str_oem:
    list_oem_temp = [oem.strip() for oem in str_oem.split(',')]
    for oem in list_oem_temp:
        if oem != '' and oem not in list_oem:
            list_oem.append(oem)

list_oem

['3L8Z6268AA', 'L30512201']

In [26]:
from urllib.parse import urljoin

In [27]:
dict_src, i, list_value = {}, 0, list_tbody[index_part].xpath('./tr[1]/td/div[contains(@class, "listing-image-space-occupy")]/input[contains(@id, "jsninlineimg[__GIP__")]/@value').getall()
for value in list_value:
    list_src = json.loads(value).get('Slots', None)
    for src in list_src:
        dict_src[str(i)] = urljoin('https://www.rockauto.com', src['ImageData']['Full'].strip())
        i += 1

dict_src = dict_src if dict_src else json.loads(dict_['kit_json_src'])

dict_src

{'0': 'https://www.rockauto.com/info/583/715F-1-ANG.jpg'}

In [28]:
span = list_tbody[index_part].xpath('./tr[1]/td[contains(@id, "listingtd[__GIP__") and contains(@id, "__][price]")]/span[contains(@id, "dprice[__GIP__") and contains(@id, "__][td]")]/span/span[contains(@id, "dprice[__GIP__") and contains(@id, "__][v]")]')[0]
price = etree.tostring(span.root).decode('utf-8')
price = re.sub(r'<.*?>', '', price)
price = re.sub(r' +', ' ', price)
price = html.unescape(price).strip()
dict_price = {'default': price}

i, list_td = 0, list_tbody[index_part].xpath('./tr[1]/td[contains(@class, "listing-inner-content")]/div/div[contains(@class, "listing-optionchoice-multiple-container")]/span[contains(@id, "ddrepl[optionchoice[__GIP__") and contains(@id, "__]][container]")]/span[@class="hide-if-js"]/select[contains(@id, "optionchoice[__GIP__")]/option[@value!=""]')
for td in list_td:
    price = etree.tostring(td.root).decode('utf-8')
    price = re.sub(r'<.*?>', '', price)
    price = re.sub(r' +', ' ', price)
    price = html.unescape(price).strip()
    if price != '':
        if i == 0:
            dict_price['choose'] = {}
        dict_price['choose'][str(i)] = price
        i += 1

dict_price

{'default': 'Out of Stock'}

In [29]:
{'kit_type': dict_['kit_type'],
 'kit_no': dict_['kit_no'],
 'kit_type_code': dict_['kit_type_code'],
 'kit_manufacturer': dict_['kit_manufacturer'],
 'kit_part_number': dict_['kit_part_number'],
 'kit_url': dict_['kit_url'],
 'kit_picture': '',
 'kit_part_code': dict_['kit_part_code'],
 'kit_join_mpntcpc': dict_['kit_join_mpntcpc'],
 'kit_not_found': 'no',
 'kit_choose': list_choose[index_part],
 'kit_json_sidenote': json.dumps(dict_sidenote),
 'kit_info_url': info_url,
 'kit_json_footnote': json.dumps(dict_footnote),
 'kit_oem': ';'.join(list_oem),
 'kit_json_src': json.dumps(dict_src),
 'kit_json_price': json.dumps(dict_price)}

{'kit_type': 'Timing Chain',
 'kit_no': 1,
 'kit_type_code': '5724',
 'kit_manufacturer': 'MELLING',
 'kit_part_number': '715F',
 'kit_url': 'https://www.rockauto.com/en/parts/MELLING,715F,Timing Chain,5724&Lennon=1',
 'kit_picture': '',
 'kit_part_code': '8306448',
 'kit_join_mpntcpc': 'MELLING;715F;5724;8306448',
 'kit_not_found': 'no',
 'kit_choose': '',
 'kit_json_sidenote': '{}',
 'kit_info_url': 'https://www.rockauto.com/en/moreinfo.php?pk=8306448&cc=0&pt=5724',
 'kit_json_footnote': '{"0": "Category: Timing Chain"}',
 'kit_oem': '3L8Z6268AA;L30512201',
 'kit_json_src': '{"0": "https://www.rockauto.com/info/583/715F-1-ANG.jpg"}',
 'kit_json_price': '{"default": "Out of Stock"}'}